name: Code Quality
on: [push]
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv lock --locked
  lint:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv sync
      - run: uvx ruff check .
  format:
    runs-on: ubuntu-latest
    needs: [lock_file, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv sync
      - run: uvx ruff format .

  check_types:
    runs-on: ubuntu-latest
    needs: [lock_file, lint, format]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv sync
      - run: uvx ty check .

  