name: Semantic Release

on:
  push:
    branches:
      - master

permissions:
  contents: write # to create release (tags)
  issues: write # to comment on released issues
  pull-requests: write # to comment on released pull requests

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release to analyze commits

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
